create user FITNESS IDENTIFIED BY fitness;

SELECT * from dba_users where username= 'FITNESS';

grant all PRIVILEGES to FITNESS;

CREATE TABLE USER_FITNESS(
USER_ID NUMBER NOT NULL PRIMARY KEY,
USER_NAME VARCHAR2(25) NOT NULL,
USER_ADDRESS VARCHAR2(50) NOT NULL,
USER_CITY VARCHAR2(25) NOT NULL,
USER_PH_NUMBER VARCHAR(25) NOT NULL
);

CREATE TABLE MEDICAL_CHECKUP(
CHECKUP_ID NUMBER,
HEIGHT DECIMAL(3,2),
WEIGHT DECIMAL(3,2),
HEART_BEAT DECIMAL(3,1),
USER_ID NUMBER NOT NULL,
PRIMARY KEY(CHECKUP_ID),
FOREIGN KEY(USER_ID) REFERENCES USER_FITNESS(USER_ID)
);

ALTER TABLE MEDICAL_CHECKUP MODIFY(
        HEIGHT NUMBER(5,2),
        WEIGHT DECIMAL(5,2));
CREATE TABLE CARDIO(
CARDIO_EX_NUM NUMBER,
USER_ID NUMBER NOT NULL,
CARDI0_EX_NAME VARCHAR2(25),
CARDIO_EX_LEVEL VARCHAR2(30),
CARDIO_EX_REP NUMBER
);

CREATE TABLE BACK(
BACK_EX_NUM NUMBER,
USER_ID NUMBER NOT NULL,
BACK_EX_NAME VARCHAR2(25),
BACK_EX_LEVEL VARCHAR2(30),
BACK_EX_REP NUMBER
);

CREATE TABLE SHOULDER(
SHOULDER_EX_NUM NUMBER,
USER_ID NUMBER NOT NULL,
SHOULDER_EX_NAME VARCHAR2(25),
SHOULDER_EX_LEVEL VARCHAR2(30),
SHOULDER_EX_REP NUMBER
);

CREATE TABLE CHEST(
CHEST_EX_NUM NUMBER,
USER_ID NUMBER NOT NULL,
CHEST_EX_NAME VARCHAR2(25),
CHEST_EX_LEVEL VARCHAR2(30),
CHEST_EX_REP NUMBER
);

CREATE TABLE ARMS(
ARMS_EX_NUM NUMBER,
USER_ID NUMBER NOT NULL,
ARMS_EX_NAME VARCHAR2(25),
ARMS_EX_LEVEL VARCHAR2(30),
ARMS_EX_REP NUMBER
);

CREATE TABLE LEG(
LEG_EX_NUM NUMBER,
USER_ID NUMBER NOT NULL,
LEG_EX_NAME VARCHAR2(25),
LEG_EX_LEVEL VARCHAR2(30),
LEG_EX_REP NUMBER
);

INSERT INTO USER_FITNESS VALUES (1, 'RAM', 'ROHINI', 'DELHI', '875090****');
SELECT * FROM user_fitness;

INSERT INTO medical_checkup VALUES (1, 166.5, 59.6, 72.0, 1);
SELECT * FROM medical_checkup;

INSERT INTO ARMS VALUES(1, 1, 'FORE-ARMS','BEGINNER',3);
SELECT * FROM arms;

INSERT INTO BACK VALUES(1, 1, 'PULL-UPS','BEGINNER',3);
SELECT * FROM back;

INSERT INTO CARDIO VALUES(1, 1, 'JUMPING JACK','BEGINNER',3);
SELECT * FROM cardio;

INSERT INTO CHEST VALUES(1, 1, 'DIPS','BEGINNER',3);
SELECT * FROM chest;

INSERT INTO LEG VALUES(1, 1, 'SQUATS','BEGINNER',3);
SELECT * FROM leg;

INSERT INTO SHOULDER VALUES(1, 1, 'ROTATOR CUFF','BEGINNER',3);
SELECT * FROM shoulder;

